# Generated by Django 3.0.7 on 2020-06-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showvideo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='discription',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='showvideo.Video'),
        ),
    ]
